Use fenced code blocks to show missing closing tags
blakedietz/vscode-snippets-liveview pull request #11
Opened 2023-07-31 15:42 UTC by aifrak

Closing tags (e.g. `</.link>`) in markdown can not be displayed with `<pre>`. The fix is to use fenced code blocks with triple backticks ``` instead.

I made a quick replace all to save time.

I know that we could do [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting), but I don't know if it would be more confusing as it is not real elixir code, rather snippet templates for elixir. If you would like syntax highlighting, just let me know.

2023-08-01 20:32 UTC, blakedietz requested changes
Thanks for finding this issue. While I do think that this fix would be  good, you'll need to make the changes here: https://github.com/blakedietz/vscode-snippets-liveview/blob/main/lib/app.ex#L157-L159.

The documentation is generated when running the commands that are located in the README.md. Let me know if I can help in any way.

2023-08-03 07:46 UTC, aifrak commented
I have reverted my previous commit and changed the code at the requested location.

2023-08-03 16:45 UTC, blakedietz commented on lib/app.ex
> +    `#{snippet.prefix |> Enum.join(",")}`
Nice catch here too. :)

2023-08-03 16:46 UTC, blakedietz commented on lib/app.ex
> +    ```
Great!

2023-08-03 16:46 UTC, blakedietz approved these changes

2023-08-03 16:47 UTC, merged